config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resource :accounts, controller: :accounts, only: [:create, :update, :destroy]
  resources :items, controller: :items, only: [:index, :create, :update, :destroy] do
    resources :accounts, only: [:index, :show]
  end
  devise_for :users
  root "items#index"

  get "/", to: "items#index"
  # get "/accounts", to: "accounts#index"
  # post "/items", to: "items#create"
  # delete "/items/:id", to: "items#destroy"

  # post "/accounts", to: "accounts#create"
  # delete "/accounts", to: "accounts#destroy"

  get "/plaid/link_token", to: "plaid#create_link_token"
  # get "/plaid/public_token_exchange/:public_token", to: "plaid#public_token_exchange"
  post "/plaid/public_token_exchange", to: "plaid#public_token_exchange"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :item
  has_many :transactions, dependent: :destroy

  validates :name, :plaid_account_id, :mask, :currency_code, :account_subtype, :account_type,
            :current_balance_cents, :available_balance_cents, :limit_cents, presence: true
  # has_many :transactions, -> { order("authorized_date desc") }, dependent: :destroy

  monetize :current_balance_cents, :available_balance_cents, :limit_cents
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/orderable_by_timestamp.rb
# frozen_string_literal: true

# module OrderableByTimestamp
#   extend ActiveSupport::Concern

#   included do
#     scope :by_most_recent, -> { order(authorized_date: :desc) }
#   end
# end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :user
  has_many :accounts, dependent: :destroy

  validates :access_token, :plaid_item_id, :bank_name, :is_active,
            :institution_id, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account

  monetize :amount_cents

  # include OrderableByTimestamp
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :accounts, through: :items, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # before_action :plaid_client, only: %w[index show create]

  def index
    @accounts = Item.find_by_id(params[:item_id]).accounts
    render "index", status: :ok
  end

  def show
    @account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController

  def index
    @items = current_user.items
    @top_merchants = Transaction::GetTopMerchants.call
    @cash_balance = Assets::GetAccounts.available_cash
    @total_asset_value = Assets::GetAccounts.total_asset_value
    @investments_balance = Assets::GetAccounts.investments_balance
    @total_liabilities_value = Liabilities::GetAccounts.total_liabilities_value
    @credit_cards_balance = Liabilities::GetAccounts.credit_cards_balance
    @loans_balance = Liabilities::GetAccounts.loans_balance
    @spend_by_category = Transaction::GetSpendByCategory.call
    @networth = Networth::CalculateNetworth.call
  end

  def create
    item_exchange_response = JSON.parse(params[:item_exchange_response])
    metadata = params[:metadata]
    item = Item::Create.call(item_exchange_response:, metadata:, user_id: current_user.id)

    if item&.valid?
      Account::FindNewAccounts.call(item)
      Transaction::FetchTransactions.call(item)
      redirect_to root_path
    else
      flash.now[:alert] = "Something went wrong"
    end
  end

  def destroy
    item = Item.find(params[:id])
    Item::DeleteItem.call(item)
    redirect_to root_path
  end

  private

  def item_params
    permit.require(:item).permit(:user_id, :access_token, :plaid_item_id, :bank_name)
  end
end

app/controllers/plaid_controller.rb
class PlaidController < ApplicationController

  def create_link_token
    client = PlaidApi::CreateClient.call
    @link_token = PlaidApi::CreateLinkToken.call(client, current_user)
    render json: @link_token
  end

  def public_token_exchange
    public_token = params[:public_token]
    access_token = PlaidApi::ExchangePublicToken.call(public_token)
    render json: access_token
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/money_helper.rb
# frozen_string_literal: true

module MoneyHelper
  def format_category_money(category_money)
    category_money.map do |category|
      [category[0], remove_currency_symbol(category[1].format)]
    end
  end

  def remove_currency_symbol(amount)
    amount.sub("$", "")
  end
end

app/helpers/plaid_helper.rb
module PlaidHelper
end

app/views/accounts/_transactions_preview.html.erb
  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
    <div class="flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full align-middle sm:px-6 lg:px-8">
          <table class="min-w-full divide-y divide-gray-300">
            <tbody class="">
              <% transactions.each do |transaction|%>
                <tr>
                  <td class="whitespace-nowrap w-40 py-1 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= transaction.name.truncate(16) %></td>
                  <td class="whitespace-nowrap w-40 px-3 py-1 text-sm text-gray-500"><%= humanized_money_with_symbol(transaction.amount) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </td>

app/views/accounts/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Account Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Balance</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Recent Transactions</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">View Account Activity</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white align-top">
            <% @accounts.each do |account| %>
              <tr>
                <td class="whitespace-nowrap py-5 pl-4 pr-3 text-sm sm:pl-0">
                  <div class="flex items-center">
                    <div class="ml-4">
                      <div class="font-medium text-gray-900"><%= account.name %></div>
                      <div class="mt-1 text-gray-500"><%= account.account_type %></div>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                  <div class="text-gray-900"><%= humanized_money_with_symbol(account.available_balance_cents) %></div>
                </td>
                <% if account.transactions.exists? %>
                  <%= render partial: "transactions_preview", locals: {transactions: account.transactions.limit(3)} %>
                  
                <% else %>
                  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                    <div class="flow-root">
                      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                        <div class="inline-block min-w-full align-middle sm:px-6 lg:px-8">
                          <table class="min-w-full divide-y divide-gray-300">
                            <tbody class="">
                              <tr>
                                <td class="whitespace-nowrap py-1 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">No Transactions</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </td>
                <% end %>
                <td class="relative whitespace-nowrap py-5 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <a href="#" class="text-indigo-600 hover:text-indigo-900">Account Activity<span class="sr-only">, Account Name</span></a>
                </td>
              </tr>
            <% end %>

            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="sm:flex sm:items-center">
    <div class="mt-4 sm:ml-4 sm:mt-0 sm:flex-none">
      <button type="button" class="block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add Account</button>
    </div>
  </div>
</div>

app/views/items/_item_details.html.erb
<div class="mx-20 px-4 sm:px-6 lg:px-8">
  <div class="mt-2 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Account Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Balance</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Recent Transactions</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">View Account Activity</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white align-top">
            <% accounts.each do |account| %>
              <tr>
                <td class="whitespace-nowrap py-5 pl-4 pr-3 text-sm sm:pl-0">
                  <div class="flex items-center">
                    <div class="ml-4">
                      <div class="font-medium text-gray-900"><%= account.name %></div>
                      <div class="mt-1 text-gray-500"><%= account.account_type %></div>
                    </div>
                  </div>
                </td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                  <div class="text-gray-900"><%= humanized_money_with_symbol(account.available_balance) %></div>
                </td>
                <% if account.transactions.exists? %>
                  <%= render partial: "accounts/transactions_preview", locals: {transactions: account.transactions.limit(3)} %>
                  
                <% else %>
                  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                    <div class="flow-root">
                      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                        <div class="inline-block min-w-full align-middle sm:px-6 lg:px-8">
                          <table class="min-w-full divide-y divide-gray-300">
                            <tbody class="">
                              <tr>
                                <td class="whitespace-nowrap py-1 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">No Transactions</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </td>
                <% end %>
                <td class="relative whitespace-nowrap py-5 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <a href="#" class="text-indigo-600 hover:text-indigo-900">Account Activity<span class="sr-only">, Account Name</span></a>
                </td>
              </tr>
            <% end %>

            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="sm:flex sm:items-center">
    <div class="mt-4 sm:ml-4 sm:mt-0 sm:flex-none mb-4">
      <button type="button" class="block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add Account</button>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="mx-20 mt-12 mb-6 flex flex-wrap">
  <p class="text-6xl font-extrabold w-full pb-4">Plaid Pattern</p>
  <p class="text-3xl font-thin pb-4 border-b border-black">
    This page shows a user's net worth, spending by category, and allows them 
    to explore account and transactions details for linked items.
  </p>
</div>
<div class="mx-20 mt-12 mb-6 py-8 flex flex-wrap justify-around shadow-xl content-center border border-gray-100">
  <div class="flex flex-wrap justify-between content-between">
    <p class="w-full font-bold text-sm mb-2">EMAIL</p>
    <p><%= current_user.email %></p>
  </div>
  <div>
    <p class="w-full font-bold text-sm mb-2">CREATED ON</p>
    <p><%= current_user.created_at.strftime('%m/%d/%Y') %></p>
  </div>
  <div>
    <p class="w-full font-bold text-sm mb-2">NUMBER OF BANKS CONNECTED</p>
    <p><%= @items.size %></p>
  </div>
</div>
<div class="mx-20 my-20 flex flex-wrap">
  <p class="text-3xl font-extrabold w-full pb-2">Net Worth</p>
  <p class="text-2xl font-thin w-full">A summary of your assets and liabilities</p>
</div>
<div class="mx-20 my-10 flex flex-wrap">
  <p class="text-lg font-thin w-full pb-4">
    YOUR TOTAL ACROSS <%= pluralize(@items.size, "bank").upcase %>
  </p>
  <p class="text-3xl font-extrabold w-full pb-2"><%= humanized_money_with_symbol(@networth) %></p>
</div>
<div class="mx-20 my-10 flex flex-wrap justify-between space-x-4">
  <div class="px-8 pt-8 pb-20 flex flex-wrap border border-gray-200 justify-between flex-1 space-y-12">
    <div class="w-full flex flex-wrap justify-between">
      <p><%= humanized_money_with_symbol(@total_asset_value) %></p>
      <p>Add Asset</p>
    </div>
    <div class="w-full">
      <p class="text-2xl font-thin">Assets</p>
    </div>
    <div class="flex flex-wrap space-y-4 font-thin">
      <div class="w-full flex space-x-2">
        <p class="flex-1">Cash</p>
        <p class="flex-1"><%= humanized_money_with_symbol(@cash_balance) %></p>
      </div>
      <div class="w-full flex space-x-2">
        <p class="flex-1">Investments</p>
        <p class="flex-1"><%= humanized_money_with_symbol(@investments_balance) %></p>
      </div>
    </div>
  </div>
  <div class="px-8 pt-8 pb-20 flex flex-wrap border border-gray-200 justify-between flex-1 space-y-12">
    <div class="w-full flex flex-wrap justify-between">
      <p><%= humanized_money_with_symbol(@total_liabilities_value) %></p>
    </div>
    <div class="w-full">
      <p class="text-2xl font-thin">Liabilities</p>
    </div>
    <div class="flex flex-wrap space-y-4 font-thin">
      <div class="w-full flex space-x-2">
        <p class="flex-1">Credit Cards</p>
        <p class="flex-1"><%= humanized_money_with_symbol(@credit_cards_balance) %></p>
      </div>
      <div class="w-full flex space-x-2">
        <p class="flex-1">Loans</p>
        <p class="flex-1"><%= humanized_money_with_symbol(@loans_balance) %></p>
      </div>
    </div>
  </div>
</div>
<div class="mx-20 my-20 flex flex-wrap">
  <p class="text-3xl font-extrabold w-full pb-2">Monthly Spending</p>
  <p class="text-2xl font-thin w-full">A breakdown of your monthly spending</p>
</div>
<div class="mx-20 mt-10 flex flex-wrap">
  <p class="text-lg font-thin w-full pb-4">
    <%= "Monthly breakdown across #{pluralize(@items.size, "bank")}".upcase %>
  </p>
</div>
<div class="mx-20 mb-10 flex flex-wrap justify-between space-x-4">
  <div class="px-8 pt-8 pb-20 flex flex-wrap border border-gray-200 justify-between flex-1 space-y-12">
    <div class="w-full">
      <p class="text-2xl font-thin">Spending Categories</p>
    </div>
    <div class="flex flex-wrap space-y-4 font-thin">
      <div class="w-full flex space-x-2">
        <p class="flex-1">
          <%= pie_chart (format_category_money(@spend_by_category)[0..1]), legend: false %>
        </p>
      </div>
    </div>
  </div>
  <div class="px-8 pt-8 pb-20 flex flex-wrap border border-gray-200 justify-between flex-1">
    <div class="w-full">
      <p class="text-2xl font-thin">Top 5 Vendors</p>
    </div>
    <div class="px-4 sm:px-6 lg:px-8">
      <div class="flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
            <table class="min-w-full">
              <thead>
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Vendor</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Amount</th>
                </tr>
              </thead>
              <tbody>
                <% @top_merchants.each do |merchant_spend| %>
                  <tr>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm text-gray-900 sm:pl-0"><%= merchant_spend[0].truncate(16) %></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= humanized_money_with_symbol(merchant_spend[1]) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="mx-20 mt-20 mb-10 flex flex-wrap justify-between">
  <div class="flex flex-wrap flex-1">
    <p class="text-3xl font-extrabold w-full pb-2">
      <%= "#{pluralize(@items.size, "Banks")} Linked" %>
    </p>
    <p class="text-lg font-thin w-full">
      Below is a list of all your connected banks. Click on a bank to views its associated accounts
    </p>
  </div>
  <button data-controller="plaid-link" class="bg-black text-white px-6 py-4 h-fit rounded-sm">
    <p class="text-xl" id="link-account">
      Add another bank <span class="text-2x ml-8">&#8250;</span>
    </p>
  </button>
</div>
<div class="">
  <% @items.each do |item| %>
    <div data-controller="renderer">
      <div class="mx-20 mb-4 py-8 px-8 flex flex-wrap shadow-lg bg-gray-100 content-center border border-gray-200 font-thin justify-between">
        <div>
          <div class="my-auto"><%= item.bank_name %></div>
          <div class="text-sm">
            <%= link_to "view details", item_accounts_path(item), data: { remote: true, action: "click->renderer#render"} %>
          </div>
        </div>
        <%= button_to "Remove Bank", item_path(item), method: :delete, class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
      <div class="hidden" data-renderer-target="display">
        <%= render "item_details", accounts: item.accounts %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaidV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-4 px-2">
      <%= render "/shared/alerts"%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if notice %>
  <p class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4" role="alert"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert"><%= alert %></p>
<% end %>